### ISSUE TITLE
Error After opening project

### ISSUE THREAD

**Issue by acepero13** [SceneMaker/VisualSceneMaker#134]
After saving some changes. If we close the project and open it again sometimes it stops and shows only the stickman and a white screen. It is very difficult to reproduce, so I copy and paste the error trace

Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at java.util.Timer.<init>(Timer.java:160)
	at de.dfki.vsm.editor.CmdBadge.<init>(CmdBadge.java:86)
	at de.dfki.vsm.editor.project.sceneflow.workspace.WorkSpacePanel.showNodesOnWorkSpace(WorkSpacePanel.java:1394)
	at de.dfki.vsm.editor.project.sceneflow.workspace.WorkSpacePanel.showCurrentWorkSpace(WorkSpacePanel.java:1372)
	at de.dfki.vsm.editor.project.sceneflow.workspace.WorkSpacePanel.<init>(WorkSpacePanel.java:208)
	at de.dfki.vsm.editor.project.sceneflow.SceneFlowEditor.<init>(SceneFlowEditor.java:163)
	at de.dfki.vsm.editor.project.ProjectEditor.<init>(ProjectEditor.java:52)
	at de.dfki.vsm.editor.EditorInstance.openProject(EditorInstance.java:415)
	at de.dfki.vsm.editor.EditorStarter$6.mouseClicked(EditorStarter.java:454)
	at java.awt.Component.processMouseEvent(Component.java:6538)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by acepero13** [comment]
This was an OS related problem. Specifically with the limit of the threads that the system was allowed to create
