### ISSUE TITLE
VSM Crashes under timeout edges with very small time lapses

### ISSUE THREAD

**Issue by mfallas** [SceneMaker/VisualSceneMaker#146]
I guess this problem is caused because the modification is to fast, updating the edge many times could create concurrency problems. However it only happens when such nodes are inside a supernode and I try to go to the previous level.
Example attached
Exception in thread "N8" java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
	at de.dfki.vsm.util.evt.EventDispatcher.convey(EventDispatcher.java:57)
	at de.dfki.vsm.runtime.interpreter.Process.handleContinuation(Process.java:483)
	at de.dfki.vsm.runtime.interpreter.Process.execute(Process.java:660)
	at de.dfki.vsm.runtime.interpreter.Process.run(Process.java:492)

[CONCURRENCY.zip](https://github.com/SceneMaker/VisualSceneMaker/files/60496/CONCURRENCY.zip)

**Comment by SceneMaker** [comment]
Done! See commit:
 https://github.com/SceneMaker/VisualSceneMaker/commit/f20b2d5fc5c339a4a9960764bf49f8b15380a1be

**Comment by gmehlmann** [comment]
What means done?  What was the reason and how did you fix It? 

Gregor 

---- SceneMaker schrieb ----
