### ISSUE TITLE
can't play or save when scene script contains comments (ClassCastException)

### ISSUE THREAD

**Issue by kjanowski** [SceneMaker/VisualSceneMaker#163]
If the scene script contains any comment lines, the project can't be saved anymore. Also, the player completely refuses to start because it is unable to save the project.
In both cases a ClassCastException is thrown for the cast between SceneComment and SceneObject.

Here is an example of the console output when I press "Play":

Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: de.dfki.vsm.model.scenescript.SceneComment cannot be cast to de.dfki.vsm.model.scenescript.SceneObject
	at de.dfki.vsm.runtime.project.RunTimeProject.getCharacters(RunTimeProject.java:331)
	at de.dfki.vsm.runtime.project.RunTimeProject.clearAgentList(RunTimeProject.java:309)
	at de.dfki.vsm.editor.EditorInstance.isAllCharacterRegistered(EditorInstance.java:603)
	at de.dfki.vsm.editor.EditorInstance.save(EditorInstance.java:485)
	at de.dfki.vsm.editor.EditorInstance.save(EditorInstance.java:475)
	at de.dfki.vsm.editor.project.sceneflow.SceneFlowToolBar$9.actionPerformed(SceneFlowToolBar.java:410)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mfallas** [comment]
Fixed dddacabc5764ae848eb0534135e9408168f8706d. Under tests
