### ISSUE TITLE
Editor freezes after playing non-existent SceneGroup

### ISSUE THREAD

**Issue by kjanowski** [SceneMaker/VisualSceneMaker#171]
Whenever a PlayScene command is reached but the requested scene cannot be found, the whole editor becomes unresponsive because of the unhandled NullPointerException.

Example stacktrace:

Exception in thread "N1" java.lang.NullPointerException
at de.dfki.vsm.model.scenescript.SceneScript.getSceneGroup(SceneScript.java:173)
at de.dfki.vsm.runtime.player.ReactivePlayer.playScene(ReactivePlayer.java:172)
at de.dfki.vsm.runtime.interpreter.Evaluator.execute(Evaluator.java:151)
at de.dfki.vsm.runtime.interpreter.Process.execute(Process.java:553)
at de.dfki.vsm.runtime.interpreter.Process.run(Process.java:492)

This Exception should be caught, and the Player should either be stopped properly or skip that scene. It would also be good to show an error message in the interface that states the name of the scene which could not be found, similar to existing messages like "Variable XYZ is not defined". Such a message would help greatly with correcting the mistake.

**Comment by acepero13** [comment]
Now, it pops up an error message indicating which **scene** wasn't found and _continues the execution_ skipping the problematic one. I am not sure whether it makes more sense to completely stop the execution rather than skipping it (@SceneMaker ?).
