### ISSUE TITLE
Plugin properties does not open on windows when building on a Mac: platform-specific JavaFX binaries are not included

### ISSUE THREAD

**Issue by fnunnari** [SceneMaker/VisualSceneMaker#262]
When building the JAR on a Mac and running the VSM jar on a Windows machine, VSM starts, but when trying to open the Properties panel, I get the following error:

```
C:\Users\MindBot\Documents\MindBot>java -jar VisualSceneMaker-4.0.2-charamel-ws-rc4.jar
Aug 09, 2022 11:27:20 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @f456018'
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:286)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
        at javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:224)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 1 more
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:273)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:286)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
        at javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:224)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

However, executing on a Mac gives no problems.

It looks like the Properties windows uses JavaFX (why?) and when building on an architecture only the binaries of that architecture are included in the JAR.

It seems that two interventions are needed:
* remove dependencies from JavaOX in the properties window (it looks like there is no need of it, it is just a bunch of text fields and labels)
* Either:
  * Include the binaries for Mac/Win/Linux when building on whatever platform
  * Append a suffix to specify on what platform the JAR has ben built, so that users are aware that JavaFX-dependent plugins will likely not work.

**Comment by chiragbhuvaneshwara** [comment]
This also affects the VSM releases posted on GitHub at this [link](https://github.com/SceneMaker/VisualSceneMaker/releases). As a short-term fix, we should consider adding a suffix to specify the platform for the JAR files in the releases.
